### ISSUE TITLE
Sandbox does not initialize the FHIRcastClientController when running an external client

### ISSUE THREAD

**Issue by eitanbehar** [fhircast/sandbox#14]
In cases where an external client is used, like FHIRcast.py from the Tutorial, the FHIRcastClientController object is not initialized, therefore a subscribption cannot be created:
FHIRcastSandbox.Controllers.FHIRcastClientController.**_internalModel_**.SubscriptionsToHub.Add(subscription);
**_FHIRCastSandbox\Rules\ValidateSubscriptionJob.cs_**
Line 25
Note that if a Refresh request is sent before subscribing, the client is initialized properly.
Somwhere in the flow it's needed an addtional:
 **_if (internalModel == null) { internalModel = new ClientModel(); }_**

**Comment by lbergnehr** [comment]
Yes, I think this is OK now.
