### ISSUE TITLE
Url verification parameters don't match the specification.

### ISSUE THREAD

**Issue by isaacvetter** [fhircast/sandbox#8]
During the May 2018 FHIR Connectathon in Koeln, @oridashi pointed out that the parameters on the url verification interaction sent by the sandbox don't match those documented in the specification.

http://fhircast.org#hub-verifies-callback-url

**Comment by isaacvetter** [comment]
I just re-encountered this, here's an HTTP GET from the Sandbox when it's acting as the server and performing the url verification:
```
"GET /?challenge=533bc2617a124afd90356382f3f6d433&callback=http%3a%2f%2flocalhost%3a1337%2f&mode=Subscribe&topic=5000-2&events=System.String%5b%5d HTTP/1.1" 200 -
```
Should be:
* challenge should be `hub.challenge`
* There ought not to be a callback parameter
* mode should be `hub.mode` (and optimally it's value would be lower-case)
* topic should be `hub.topic`
* events should be `hub.events` and should be serialized correctly
* There should be a `hub.lease_seconds`

The [table in the spec](http://fhircast.org/#hub-verifies-callback-url) is a useful comparison.

**Comment by oridashi** [comment]
I have not done my pull request cleanup after Connectathon, still catching up.  Think I should start again and do a cleaner request for this one.
